POST http://localhost:3000/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2019-05-01",
  "type": "OccupationalHealthcare",
  "specialist": "dr. Test",
  "description": "test.",
  "employerName": "Test employer"
}